### ISSUE TITLE
Issues with SMPLX_NEUTRAL.npz

### ISSUE THREAD

**Issue by shreyakumar21** [naver/multi-hmr#11]
This folder/file is not available on the website. Could you please redirect me to the specific website that contains this?

Thank you!

**Comment by fabienbaradel** [comment]
Related to #10 . Please have a look to the README, we explained how to download this file in the paragraph [INSTALLATION](https://github.com/naver/multi-hmr?tab=readme-ov-file#installation).

**Comment by khaitha** [comment]
Thank you
