### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by khaitha** [naver/multi-hmr#12]
![issue](https://github.com/naver/multi-hmr/assets/97413947/4c7fa776-660f-4ef1-a9b5-12b9b3e001a3)

As the image states im getting this error which I do not how to proceed from

**Comment by khaitha** [comment]
And also I downloaded the netural file from here: https://huggingface.co/camenduru/SMPLer-X/blob/main/SMPLX_NEUTRAL.npz
because the website mentioned in the github does not have the neutral file

**Comment by fabienbaradel** [comment]
Ok thanks for your comment.

**Comment by wyt1234** [comment]
https://smpl-x.is.tue.mpg.de/download.php
