### ISSUE TITLE
CUFFS dataset release

### ISSUE THREAD

**Issue by SWWdz** [naver/multi-hmr#14]
Thanks for your work! I have a problem annotating the SMPL-X parameters. Can you tell me how to annotate my image with SMPL-X parameters.

**Comment by SWWdz** [comment]
You mentioned the Synthetic whole-body CUFFS dataset in your article. How can I download the data set?

**Comment by fabienbaradel** [comment]
Oh I see, sorry. For the moment I cannot give you a date for the release. I will keep you updated as soon as we release the data.

**Comment by fabienbaradel** [comment]
Hi @SWWdz , CUFFS dataset is now available [here](https://download.europe.naverlabs.com/ComputerVision/MultiHMR/CUFFS/).
The zip file contains images and a pkl file with annotations. I will provide soon more info about how to process it. Stay tuned.

**Comment by SWWdz** [comment]
Thanks for your share!

**Comment by nehc0** [comment]
> Hi @SWWdz , CUFFS dataset is now available [here](https://download.europe.naverlabs.com/ComputerVision/MultiHMR/CUFFS/). The zip file contains images and a pkl file with annotations. I will provide soon more info about how to process it. Stay tuned.

Hi @fabienbaradel , the only pkl file contained in the zip file is `humgen3d_EFH_like_all.pkl` , which is empty. Is the annotations not available yet?

**Comment by fabienbaradel** [comment]
The new zip file now contains images, license and annotation file called ```cuffs_annots_20240905.pkl```.
You can find SMPL-X parameters for each human in this directory.
I will release soon the associated dataloader, stay tuned.

**Comment by nehc0** [comment]
> The new zip file now contains images, license and annotation file called `cuffs_annots_20240905.pkl`. You can find SMPL-X parameters for each human in this directory. I will release soon the associated dataloader, stay tuned.

That's great, thanks! I still have a question: is it that the dataset doesn't have facial expression parameters as in BEDLAM? I found the parameters in that pkl file don't consist of expression parameters.

**Comment by fabienbaradel** [comment]
Yes you are right.

**Comment by SWWdz** [comment]
Do you use the optimization method to get smplx parameters from your 2D observation? I am interested in how to get the GT label parameters of humans in smplx parametric model.

**Comment by fabienbaradel** [comment]
@SWWdz , the pipeline for generating imgaes are annotations is described in the paper (see supp. mat.), I encourage you to look at the CUFFS dataset section to get all the details. In short, we sample SMPL-X parameters, generate the SMPL-X mesh and do a retargetting to Human Generator mesh using optimization and finally do the rendering. I hope that my answer helps for your work.

**Comment by nehc0** [comment]
> @SWWdz , the pipeline for generating imgaes are annotations is described in the paper (see supp. mat.), I encourage you to look at the CUFFS dataset section to get all the details. In short, we sample SMPL-X parameters, generate the SMPL-X mesh and do a retargetting to Human Generator mesh using optimization and finally do the rendering. I hope that my answer helps for your work.

Hello. I'm just confirming that the SMPL-X model you used to generate mesh is 'neutral' gender right?

**Comment by fabienbaradel** [comment]
Yep!
