### ISSUE TITLE
Joints rotations and position

### ISSUE THREAD

**Issue by sebastianopazo1** [naver/multi-hmr#16]
Hi! Great work with this project. 
Is it possible to obtain the joint's rotations and position from the model?
Thanks for your help!

**Comment by fabienbaradel** [comment]
Hi @sebastianopazo1 , thanks for your interest in our work. Good point, I will update the code to output rotations and 3d positions by the end of the week. I will keep you updated 😄

**Comment by fabienbaradel** [comment]
Hi @sebastianopazo1 , finally I see that it is already possible to obtain what you want.
The joint's rotations can be obtained [here](https://github.com/naver/multi-hmr/blob/master/model.py#L228) and the position of the pelvis [here](https://github.com/naver/multi-hmr/blob/master/model.py#L227).
I hope that it helps,

**Comment by sebastianopazo1** [comment]
Hi @fabienbaradel! Thank you so much! I'll take a look at it :)

**Comment by sebastianopazo1** [comment]
Hello @fabienbaradel Thanks for your help to obtain the joint rotations. I'm trying to replicate the movement of the SMPL-X model in Unity, for that i need to know the exact order of the joints and its values. Could you provide me the order of the joints? Thank you for your help!

**Comment by fabienbaradel** [comment]
Hi @sebastianopazo1 , SMPL-X joint names can be found [here](https://github.com/vchoutas/smplx/blob/1265df7ba545e8b00f72e7c557c766e15c71632f/smplx/joint_names.py#L19).
They correspond to the joints that our method is outputing [here](https://github.com/naver/multi-hmr/blob/master/model.py#L233). Please check if the translation is included in ```j3d_smplx```.
I hope that it helps to solve your issue,

**Comment by sebastianopazo1** [comment]
Thanks for all your help @fabienbaradel. I'm that order, but I'm not getting the expected result. Right now I'm using the 'rotmat' output instead of the 'rotvec' and then transforming it to quaternions using RoMa library. This transformation might be wrong or maybe I'm extracting the wrong information from the output. 
Sorry for bodering you and thanks again for your help!

**Comment by fabienbaradel** [comment]
Hi @sebastianopazo1 , I see. Maybe check the kinematic tree from the ```smplx``` [github repo](https://github.com/vchoutas/smplx). Maybe the joints are not located at the same position as in your kinematic tree. Hope it helps and good luck for your project!

**Comment by sebastianopazo1** [comment]
Hi @fabienbaradel. I managed to transform the values correctly. The only thing is that I'm obtaining the pose of 53 joints instead of the usual 55. Is this normal? Thanks again for your help!

**Comment by fabienbaradel** [comment]
Hi @sebastianopazo1 , yes ```rotvec``` is of shape (53,3) so that's normal. We are not using the ```eye_pose``` in our work ([please have a look to our output](https://github.com/naver/multi-hmr/blob/master/blocks/smpl_layer.py#L88-L92))

**Comment by roshanbiswanath** [comment]
How can I find out which joint given in 
[https://github.com/vchoutas/smplx/blob/1265df7ba545e8b00f72e7c557c766e15c71632f/smplx/joint_names.py#L19](url)
corresponds to which index of rotvec in
[https://github.com/naver/multi-hmr/blob/master/blocks/smpl_layer.py#L88-L92](url)

**Comment by luoww1992** [comment]
@sebastianopazo1 
have you got the quats by RoMa or other libs like mathutils ?
