### ISSUE TITLE
Extrinsic parameters

### ISSUE THREAD

**Issue by sebastianopazo1** [naver/multi-hmr#18]
Hi! I'm having some trouble obtaining the extrinsic parameters of the camera, such as the rotation and position. Is it possible to calculate them with the project? 
Thank you very much for your help!

**Comment by fabienbaradel** [comment]
Hi @sebastianopazo1 
Multi-HMR is expressing humans in camera coordinate system and the method do not output extrinsics parameters.
Reconstructing both humans and camera in world coordinates system would be an interesting topic to work on.
I hope that it answered your question,

**Comment by sebastianopazo1** [comment]
I understand, thanks for your help and great job with the project!
