### ISSUE TITLE
[Question] About 3d visualization tool or somethig?

### ISSUE THREAD

**Issue by chojinie** [naver/multi-hmr#2]
Hi there,
I'm Jin who studying 3d Whole body estimation.
First, very thanks to share nice work!

I'am anticipating share entire source code. HaHa..

Anyway, Could you tell me which tool or method was used to rotate and visualize the 3D mesh in three-dimensional space?

Sincerely,

**Comment by fabienbaradel** [comment]
Hi @chojinie 
Thanks a lot.
We use ```trimesh``` and ```pyrender``` both for creating the 3D scene and doing the rendering.
Please find the function [here](https://github.com/naver/multi-hmr/blob/master/utils/render.py#L175) for rendering the set of 3D meshes.
If your question is about the teaser figures from the README, then we did the rendering using ```render_meshes``` by moving the [camera position](https://github.com/naver/multi-hmr/blob/master/utils/render.py#L287).
Hope it helps for your work.

**Comment by chojinie** [comment]
Thank you @fabienbaradel .
I'm learning something new thanks to you. 😌

**Comment by chojinie** [comment]
Thank you @fabienbaradel .
I'm learning something new thanks to you. 😌
