### ISSUE TITLE
How to save SMPLX/SMPL output?

### ISSUE THREAD

**Issue by IceFtv** [naver/multi-hmr#20]
Very nice job! I want to know how to save the predicted SMPLX/SMPL parameters, including body_pose, etc. 
Looking forward to your reply. Thanks.

**Comment by fabienbaradel** [comment]
Hi @IceFtv , thanks for your interest in our work. The SMPL-X parameters can be found [here](https://github.com/naver/multi-hmr/blob/master/model.py#L225-L230). ```rotvec``` corresponds to the concatenation of the ```global_orient```, ```body pose```, ```left_hand_pose```, ```right_hand_pose``` and ```jaw_pose``` expressed in rotation vector. You can found this information in the output dictionary of the forward function.
I hope that I answered your question.
Best,

**Comment by kaenkogashi** [comment]
hi, @fabienbaradel , Thank you for your great work!

According to SMPL-X site (https://github.com/vchoutas/smplx). It says , there are three parameters θ, β, ψ.

>Description
>SMPL-X (SMPL eXpressive) is a unified body model with shape parameters trained jointly for the face, hands and body. SMPL->X uses standard vertex based linear blend skinning with learned corrective blend shapes, has N = 10, 475 vertices and K = 54 >joints, which include joints for the neck, jaw, eyeballs and fingers. SMPL-X is defined by a function M(θ, β, ψ), where θ is the >pose parameters, β the shape parameters and ψ the facial expression parameters.

 I want to know how to save the predicted SMPLX parameters θ, β, ψ ?
Thank you in advance.

**Comment by kaenkogashi** [comment]
hi, @fabienbaradel  , Thank you for your answer.

>SMPL-X is defined by a function M(θ, β, ψ), where θ is the pose parameters, β the shape parameters and ψ the facial expression parameters.

From my debug results, I think SMPL-X's betas β  is below
>shape = pred_smpl_params['betas']
 
pose and facial expression, θ and ψ  are include in the rotvec ([1, 53, 3]), and the joints name order are like below.
Please let me know if my understanding is wrong.
   { "pelvis",
    "left_hip",
    "right_hip",
    "spine1",
    "left_knee",
    "right_knee",
    "spine2",
    "left_ankle",
    "right_ankle",
    "spine3",
    "left_foot",
    "right_foot",
    "neck",
    "left_collar",
    "right_collar",
    "head",
    "left_shoulder",
    "right_shoulder",
    "left_elbow",
    "right_elbow",
    "left_wrist",
    "right_wrist",
    "left_index1",
    "left_index2",
    "left_index3",
    "left_middle1",
    "left_middle2",
    "left_middle3",
    "left_pinky1",
    "left_pinky2",
    "left_pinky3",
    "left_ring1",
    "left_ring2",
    "left_ring3",
    "left_thumb1",
    "left_thumb2",
    "left_thumb3",
    "right_index1",
    "right_index2",
    "right_index3",
    "right_middle1",
    "right_middle2",
    "right_middle3",
    "right_pinky1",
    "right_pinky2",
    "right_pinky3",
    "right_ring1",
    "right_ring2",
    "right_ring3",
    "right_thumb1",
    "right_thumb2",
    "right_thumb3",
    "jaw", }

**Comment by fabienbaradel** [comment]
Hi, `facial expression` is not included in the `rotvec`.
The ordering that we use is given [here](https://github.com/naver/multi-hmr/blob/master/blocks/smpl_layer.py#L84-L97).

**Comment by kaenkogashi** [comment]
hi, @fabienbaradel , Thank you for your response.

>Hi, facial expression is not included in the rotvec.
I didn't write facial expression above except jaw.

Although I think  jaw shall include into the facial expression...?

**Comment by fabienbaradel** [comment]
Nope. Jaw is in the rotvec, facial expression is different.

**Comment by kaenkogashi** [comment]
Hi, @fabienbaradel , I think everything is clear. Thank you very much.

**Comment by luoww1992** [comment]
@kaenkogashi 
the sort of your gived: { "pelvis", "left_hip", ...... "jaw", } is right ?

i use it to get 22 smpl rotation from rotvec[:22] , and add twos rotvec with 0, 
then i use nosmpl to show it , but it shows wrong pose,

https://github.com/naver/multi-hmr/issues/35#issuecomment-2337778339

**Comment by kaenkogashi** [comment]
@luoww1992 

Yes, it works for me!

>then i use nosmpl to show it , but it shows wrong pose,
I guess your tool have some bugs !?
![image](https://github.com/user-attachments/assets/b2e52bb5-0449-4683-ad20-a67ff4624e0e)

**Comment by luoww1992** [comment]
@kaenkogashi ， i test it with the new code insted:
    body = np.vstack((data[:22], np.array([0, 0, 0]))).reshape(1, -1, 3).astype(np.float32)
    global_orient = np.array([0, 0, 0]).reshape(1, -1, 3).astype(np.float32)
then it looks good.

After i show it in UE5， it looks bad pose with buleprint: Set Bone Rotation By Name.
how ?

**Comment by kaenkogashi** [comment]
I think this is the problem with UE5, I don't know how to use UE5.
