### ISSUE TITLE
Release of "multiHMR_S" and "MultiHMR-B"

### ISSUE THREAD

**Issue by zhengchangren95** [naver/multi-hmr#21]
Thank you for your great work!

Are you going to release other pretrained models such as "MultiHMR-S" and "MultiHMR-B"? I would really appreciate it if you could release them.

**Comment by fabienbaradel** [comment]
Hi @zhengchangren95 , thanks for your interest in our work. We will release in the coming weeks new checkpoints. For the moment we have to a wait a bit due to license issue that we need to solve first.
Thanks for your understanding.

**Comment by zhengchangren95** [comment]
> Hi @zhengchangren95 , thanks for your interest in our work. We will release in the coming weeks new checkpoints. For the moment we have to a wait a bit due to license issue that we need to solve first. Thanks for your understanding.

Thank you so much!

**Comment by fabienbaradel** [comment]
Hi @zhengchangren95 , today we are releasing training and validation code as well as new checkpoints with smaller backbone. Please have look to our [PRETRAINED MODELS](https://github.com/naver/multi-hmr?tab=readme-ov-file#pre-trained-models).
