### ISSUE TITLE
missing smplx2smpl.pkl

### ISSUE THREAD

**Issue by olga-2020-Feb** [naver/multi-hmr#24]
Hello,
Thank you for you work!
Where can I download smplx2smpl.pkl?

**Comment by fabienbaradel** [comment]
Hi @olga-2020-Feb , happy that you are interested by our work.
You can download ```smplx2smpl.pkl``` by running this [command line](https://github.com/pixelite1201/BEDLAM/blob/master/fetch_demo_data.sh#L39) from the BEDLAM repo. You should create an account in the [BEDLAM webpage](https://bedlam.is.tue.mpg.de/). Then unzip the file and place the file in ```models/smplx/smplx2smpl.pkl```.
Hope it helps.

**Comment by olga-2020-Feb** [comment]
Thank you very much!!
