### ISSUE TITLE
Error with the new checkpoints

### ISSUE THREAD

**Issue by sebastianopazo1** [naver/multi-hmr#25]
Hi there! I was attempting to use the checkpoints to infer on some images, but I get the following error.

**SMPLX found
SMPL mean params is already here
Loading model
Traceback (most recent call last):
  File "/home/seba/Documents/multi-hmr/demo.py", line 283, in <module>
    model = load_model(args.model_name)
  File "/home/seba/Documents/multi-hmr/demo.py", line 92, in load_model
    for k,v in vars(ckpt['args']).items():
KeyError: 'args'**
I'm using the same command, but with different checkpoint name
Thank for your help!

**Comment by syleemrl** [comment]
I have the same problem. Key of new checkpoints is dict_keys(["state_dict_model") only, but those of older one have dict_keys(['epoch', 'iter', 'model_state_dict', 'args', 'scaler', 'best_val']).

**Comment by fabienbaradel** [comment]
Hi @syleemrl @sebastianopazo1 , thanks for checking the new checkpoints. Indeed the ```'args'``` key with associated values was missing, sorry about that.
I have just updated the new 672 checkpoints and it should work now.
Please delete the ckpt and download them again from the website.
It should solve the issue

**Comment by syleemrl** [comment]
@fabienbaradel It works! Thank you

**Comment by sebastianopazo1** [comment]
Thanks @fabienbaradel !
