### ISSUE TITLE
Run on a batch of images at a time

### ISSUE THREAD

**Issue by koushikam** [naver/multi-hmr#3]
Hi, Thanks for sharing your work. Currently, your code takes one image at a time. Can we extend this to a batch of images? I tried implementing it but it is throwing an error.

Thanks..

**Comment by BenjiKCF** [comment]
Yeah, I wonder it can use Video temporal information like this too. [CLIFF](https://github.com/haofanwang/CLIFF/tree/main)

**Comment by fabienbaradel** [comment]
Hi @koushikam and @BenjiKCF 
This could be indeed a very interesting feature which is not supported at the moment. We do not plan to release this feature (batching multiple images) and temporal smoothing for the moment. I keep you posted if we start working on this.

**Comment by fabienbaradel** [comment]
Since there is no plan for adding this feature for the moment I am closing the issue. I may re-open it in a near future.
Thanks!
