### ISSUE TITLE
About results of model

### ISSUE THREAD

**Issue by tuan02092000** [naver/multi-hmr#30]
Hi there, thanks to share your work.

I want to ask a bit about the coordinates of people in 3D space. When I tried running some images, the output showed people overlapping each other. How can I improve this issue?

![hi-res-889459bae3dbbec1580ca40878206afe_crop_exact_multiHMR_896_L](https://github.com/user-attachments/assets/8ceeee04-6467-4a56-9b55-acadb61a4fc6)

**Comment by fabienbaradel** [comment]
Hi, thanks for your interest in our work. Even if our method is reaching SOTA results on multiple benchmarks we are still facing this kind of limitations. I would recommend doing a temporal aggregation to smooth or correct the 3D reconstruction.
Or finetuning the model on data where you have multiple person close to each other would be a potential solution as well. I hope that my answer helps but I am sorry to not give you a straightforward answer. Good luck for your project.

**Comment by tuan02092000** [comment]
Thanks for your reply. I want to ask more about the evaluation on AGROA dataset, can you guide or provide the source code for evaluation?

**Comment by fabienbaradel** [comment]
Hi @fabienbaradel , we do not plan to provide code for evaluating on AGORA for the moment. I will let you know if we do so in a near future.
