### ISSUE TITLE
Checkpoint for higher resolusion?

### ISSUE THREAD

**Issue by ChiSu001** [naver/multi-hmr#34]
Hi! I notice that Multi-HMR has achieved 95.9 FB-MVE(smplx) and 61.1 MVE(smpl) on AGORA-test. 
On AGORA leaderboard pages you mentioned that the resolusion was 1288x1288, while in the paper (latest version) the resolusion was 896x896. I wonder which one is correct and will you release the checkpoint for higher resolusion(1288x1288)?

**Comment by fabienbaradel** [comment]
Hi, thanks for your interest in our work.
Checkpoints trained at high-resolution (used for AGORA and BEDLAM benchmarks) are now available:
- [multiHMR_1288_L_agora](https://download.europe.naverlabs.com/ComputerVision/MultiHMR/multiHMR_1288_L_agora.pt)
- [multiHMR_1288_L_bedlam](https://download.europe.naverlabs.com/ComputerVision/MultiHMR/multiHMR_1288_L_bedlam.pt)

I hope that it helps you,

**Comment by luoww1992** [comment]
@fabienbaradel 
the new models with val results show ?

**Comment by fabienbaradel** [comment]
Sorry but I do not understand your question. The ckpt that we are releasing have been fine-tuned on AGORA(train+val) and BEDLAM(train_val) and we use them for the online leaderboard for both AGORA and BEDLAM.
You can find the leaderboard here:
- [AGORA](https://agora-evaluation.is.tuebingen.mpg.de/)
- [BEDLAM](https://bedlam-leaderboard.is.tuebingen.mpg.de/leaderboard)

**Comment by ChiSu001** [comment]
> Hi, thanks for your interest in our work. Checkpoints trained at high-resolution (used for AGORA and BEDLAM benchmarks) are now available:
> 
> * [multiHMR_1288_L_agora](https://download.europe.naverlabs.com/ComputerVision/MultiHMR/multiHMR_1288_L_agora.pt)
> * [multiHMR_1288_L_bedlam](https://download.europe.naverlabs.com/ComputerVision/MultiHMR/multiHMR_1288_L_bedlam.pt)
> 
> I hope that it helps you,

Thank you!
