### ISSUE TITLE
how to use if use yolo ?

### ISSUE THREAD

**Issue by luoww1992** [naver/multi-hmr#35]
i  get human bbox by use yolo8 from image，then i see the func forward code in model.py.
i find you use the project: shubham-goel/4D-Humans to get base smpl pose.

q1, in model.py --  class Model() -- func def detection(),  what the idx is?  the index of label ?  

q2. the self.x_attention_head=HPH(...) is used to get head and body base pose by 4D-Humans ?

q3, if q2 is yes, can i use yolo to replace some code ?

q4, if i use the original code from class SMPLTransformerDecoderHead(nn.Module):  in 4D-Humans, 
can i get the same result ? or a litter different ?
-----------
q0 -- other :  a plan abou onnx or tensorrt for a higher fps ?

**Comment by fabienbaradel** [comment]
Hi, the goal of this project it to do both detection and regression using a single network. So we do not build on top of yolo detector.
- q1: idx corresponds to the coarse primary keypoint locations
- q2: it is an extension of head propose by 4D-Humans
- q3/q4: you cannot use 4D-Humans code to get the results. There are two disctints methods.
- q0: no plan to release onnx/tensorrt at the moment.
Best,

**Comment by luoww1992** [comment]
@fabienbaradel

**Comment by fabienbaradel** [comment]
It corresponds to the token location and not (x,y) location in pixel space :)

**Comment by coolkidmacho** [comment]
Is there a method to get the X and Y pixel locations of a joint?

**Comment by fabienbaradel** [comment]
@coolkidmacho this [output](https://github.com/naver/multi-hmr/blob/master/model.py#L254) gives you X/Y pixel locations of SMPL-X joints.

**Comment by luoww1992** [comment]
@fabienbaradel 
What is the orientation of the coordinate system ？

**Comment by fabienbaradel** [comment]
It is a left-hand coordinate system:
- X is going from left to right
- Y is going from bottom to top
- Z is going forward

**Comment by luoww1992** [comment]
@fabienbaradel 
i use a picture to test, but the result is not good.
and i use nosmpl to see , the show is wrong,
my data: 
[Ques.zip](https://github.com/user-attachments/files/16929329/Ques.zip)

**Comment by fabienbaradel** [comment]
I think that the issue is now solved. Feel free to ask me to re-open it
