### ISSUE TITLE
Camera intrinsic is always provided at inference

### ISSUE THREAD

**Issue by xyang35** [naver/multi-hmr#36]
Hi,

Congrats on your great work and thanks for releasing the codes and models!

 I have a question about the optional camera intrinsic input. It seems the released code assumes the camera intrinsic is always provided at inference and doesn't support `K=None` as input for the model. What if we don't have the camera intrinsic (or not able to estimate it)? Thanks.

**Comment by fabienbaradel** [comment]
Hi @xyang35 , thank for your interest in our work. Indeed we always give camera intrinsic to the model even if sometimes we do not know them. If that's the case then we use some kind of "fake" camera intrinsic (i.e. principal point at the center fo the image and focal such that the field-of-view is equal to 60). Please look at [how to do that](https://github.com/naver/multi-hmr/blob/master/demo.py#L206) in the demo code.

**Comment by xyang35** [comment]
Thanks!
