### ISSUE TITLE
Strange Results with Custom FOV

### ISSUE THREAD

**Issue by slayyden** [naver/multi-hmr#37]
I am attempting to run multi-hmr on some synthetic data meant to emulate footage from a front-facing smartphone camera.

Running the demo results in the following image:
![camtest_fov_60](https://github.com/user-attachments/assets/43044d95-4632-495e-8e28-ecb57b8ccc6c)

If I try to input the fovx of the camera (54 degrees) by modifying the following line in `demo.py`
```
parser.add_argument("--fov", type=float, default=54)
```
I get the following image:
![camtest_fov_54](https://github.com/user-attachments/assets/e9b552e2-155a-43b4-9ca2-c8fdfab21500)

The silhouette somewhat matches, but the camera is very far back and the rendered face looks flattened compared to the face in the input image. To me, this indicates that the fov is too low. 

If I instead input the fovy of the image (85 degrees) I get:
![camtest_fov_85](https://github.com/user-attachments/assets/9d7bc2b4-d420-451c-9819-fa459e54cd2e)

The facial features look no longer flattened, but the model's position is completely off and the camera is still further back than it should be. 

Which FOV was the correct one to use? I suspect that the fovy input was correct, but too far from the range of fovs the model was trained on, thus producing a strange output.

**Comment by fabienbaradel** [comment]
Hi @slayyden ,
Thank for your interest in our work. Your synthetic data looks nice!
We train Multi-HMR using mostly synthetic data where the FOV is ranging from 50 to 70 degrees and the average FOV is 60 degrees, and maybe 80% of the images have this average FOV. So I guess that Multi-HMR is not very robust to very low of very high FOV, that would be a good extension to do for sure.

So I would say to use the default FOV (60 degrees) or to use your FOVX.
The best would be to fine-tune Multi-HMR using your synthetic data with the camera parameters to make the model more rosbut.
I hope that my answer helps,
Thanks,
