### ISSUE TITLE
Demo error : libGL error: failed to create dri screen

### ISSUE THREAD

**Issue by MD-Student** [naver/multi-hmr#44]
Has anyone encountered libGL error when running the demo code?
I have followed the installation guide to prepare python environment. The model weights can be loaded successfully, but then it throws libGL error. How could I fix it?
I would be glad if anyone could offer any help. Thanks!
![image](https://github.com/user-attachments/assets/bb0b8fc9-b6bf-46ca-8aa4-d89e31e140e4)

**Comment by SWWdz** [comment]
I also get this problem. 
Do you solve this problem?

**Comment by fabienbaradel** [comment]
Hi, you are encountering a OpenGL issue.
Please could you look at this related issue: https://github.com/naver/multi-hmr/issues/23
This should solve your problem. Thanks!

**Comment by MD-Student** [comment]
> Hi, you are encountering a OpenGL issue. Please could you look at this related issue: #23 This should solve your problem. Thanks!

Thank you very much!

**Comment by MD-Student** [comment]
> I also get this problem. Do you solve this problem?

I solved this problem by change the **PYOPENGL_PLATFORM** variable to osmesa.

` os.environ["PYOPENGL_PLATFORM"] = "osmesa" #'osmesa'  `
