### ISSUE TITLE
Invalid Url of Model `multiHMR_896_L_synth.pt`

### ISSUE THREAD

**Issue by lithiumice** [naver/multi-hmr#45]
Great work!

However, when I attempt to run app.py, it appears that there might be an issue with the file path or link. 

`https://download.europe.naverlabs.com/ComputerVision/MultiHMR/multiHMR_896_L_synth.pt`

Could you please check the path and ensure that the file is accessible?

**Comment by fabienbaradel** [comment]
Hi, sorry but this file is not accessible. You can find here a list of pretrained models that we are releasing: https://github.com/naver/multi-hmr?tab=readme-ov-file#pre-trained-models
