### ISSUE TITLE
will CUFFS dataset open source?

### ISSUE THREAD

**Issue by nehc0** [naver/multi-hmr#5]
Hey, guys. I wonder do you have a plan to open source the CUFFS dataset?

**Comment by fabienbaradel** [comment]
Hi @nehc0 
Thanks for your interest. We plan to open source CUFFS but I cannot give you a release date for the moment. I will keep you updated in this issue.

**Comment by fabienbaradel** [comment]
Closing this issue for the moment, we will re-open it and add details about the release to the README.md as soon as we can.

**Comment by fabienbaradel** [comment]
CUFFS released, please see #14
