### ISSUE TITLE
Value Error

### ISSUE THREAD

**Issue by SWWdz** [naver/multi-hmr#6]
![image](https://github.com/naver/multi-hmr/assets/104372768/a8f787b4-a795-4bb2-b1c9-745bfacb94b1)
There is a error when I run the demo.py. It report there are invalid device in EGL.

**Comment by fabienbaradel** [comment]
Hi @SWWdz , do you have a GPU on your machine? And is your GPU supporting EGL? You can try to do rendering with ```osmesa``` if you are on mac.
Please have look to this [issue](https://github.com/mmatl/pyrender/issues/247#issuecomment-1486423328)

**Comment by SWWdz** [comment]
Thanks for your reply! I have GPU on my machine. I use NVIDIA TITAN XP GPU on ubuntu.

**Comment by fabienbaradel** [comment]
I recommend you to do offscreen rendering.
Is your issue solved? Thanks

**Comment by SWWdz** [comment]
![image](https://github.com/naver/multi-hmr/assets/104372768/261a0335-e954-4238-bde2-3ee742dc3f83)
I can't do offscreen rendering. In this code, num_devices == 0. And it will run error in next line:
    if not success or num_devices.value < 1:
        return []
So it will return None.

**Comment by fabienbaradel** [comment]
Hi @SWWdz but the issue that you are facing is out of the scope of this rep. I recommend you to open an issue in pyrender or opengl repos.

**Comment by fabienbaradel** [comment]
Closing this issue since it is not related to this project.
