### ISSUE TITLE
About PCOD metric

### ISSUE THREAD

**Issue by nguyenquivinhquang** [naver/multi-hmr#7]
Thanks for your wonderful work. I have a quick question:

I have read the paper and see that we use PCOD to evaluate the pelvis depth of each person in the image. How can we calculate this number, and Could you share any repo/code that calculates this metric?

Thank you,
Vinh Quang

**Comment by fabienbaradel** [comment]
Hi @nguyenquivinhquang , thanks for your interest in our work.
The orginal definition of the PCOD (percentage of correct ordinal depth) comes from this paper: ["SMAP: Single-Shot Multi-Person Absolute 3D Pose Estimation", Zhen et al, CCV'20 ](https://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123600545.pdf).
I found a code for computing this metric [here](https://github.com/boycehbz/GroupRec/blob/8a13794ff4aa7e159106544097f85432c6cfc25c/utils/eval_utils.py#L106).
I hope that it helps.

**Comment by nguyenquivinhquang** [comment]
Thank you very much for this reply. I will close the issues.
