### ISSUE TITLE
Is there an error in smpl_layer when "person_center" is None?

### ISSUE THREAD

**Issue by Liujc1998** [naver/multi-hmr#8]
In file blocks/smpl_layer.py, line 131:
transl_up = transl_up + pelvis[:,0]  should be  transl_up = transl_up - pelvis[:,0]?

**Comment by fabienbaradel** [comment]
Hi @Liujc1998 , thanks for your interest in our work.
If you use ```person_center=None``` it means that we follow the translation definition of the original [SMPL-X layer](https://github.com/vchoutas/smplx) which corresponds to the translation of the pelvis + a certain "offset" according to the shape of the person. SMPL-X authors are giving a recap of how the parametric 3d model works [here](https://www.dropbox.com/scl/fi/zkatuv5shs8d4tlwr8ecc/Change-parameters-to-new-coordinate-system.paper?dl=0&rlkey=lotq1sh6wzkmyttisc05h0in0).
So in file [blocks/smpl_layer.py, line 131](https://github.com/naver/multi-hmr/blob/master/blocks/smpl_layer.py#L131), up to my knowledge there is no error and it should be:
```transl_up = transl_up + pelvis[:,0]```
I hope that my answer helps.

**Comment by MPForte** [comment]
This is the image when I use the head to center the person (person_center_idx = 15):
![Image](https://github.com/user-attachments/assets/a4b92c2a-9bc5-44ae-9b18-7383d0b518c9)

This is the image when I use the pelvis to center the person (person_center_idx = 0):
![Image](https://github.com/user-attachments/assets/76ad0194-abc8-4359-b931-b8ea535bbbe4)

1. transl_up = transl_up 
2. transl_up = transl_up + pelvis[:,0]
3. transl_up = transl_up - pelvis[:,0] 
all bring to a not overlaid output.

@Liujc1998  did you solve it?
@fabienbaradel is it possible to get help with this?

**Comment by fabienbaradel** [comment]
Hi @MPForte ,
You cannot modify the ```person_center`` at inference time. The model has been trained with ```person_center='head'``` so you need to use this setting at inference time as well.
